//! Tauri command layer — one module per feature area, glob-re-exported from `lib.rs`.
//!
//! `#[macro_use]` on each submodule cascades the per-command `__cmd__*` /
//! `__tauri_command_name_*` macros (generated by `#[tauri::command]`) up into
//! `commands`, which `lib.rs` re-`#[macro_use]`s so `bootstrap::run`'s
//! `generate_handler![...]` resolves the bare command names.

#[macro_use]
pub(crate) mod bulk_replace;
#[macro_use]
pub(crate) mod copy_apply;
#[macro_use]
pub(crate) mod device;
#[macro_use]
pub(crate) mod doctor;
#[macro_use]
pub(crate) mod edit_tools;
#[macro_use]
pub(crate) mod held_edit;
#[macro_use]
pub(crate) mod level_footswitch;
#[macro_use]
pub(crate) mod level_preset;
#[macro_use]
pub(crate) mod level_scenes;
#[macro_use]
pub(crate) mod library;
#[macro_use]
pub(crate) mod media;
#[macro_use]
pub(crate) mod migration;
#[macro_use]
pub(crate) mod presets;
#[macro_use]
pub(crate) mod settings;
#[macro_use]
pub(crate) mod setlists;
#[macro_use]
pub(crate) mod songs;
