import type { BlockRow } from "./types";

export const CABS_BASS: readonly BlockRow[] = [
  [
    "ACD_Redhead210",
    "SWR-210",
    "cab2",
    "bass",
    "2X10 SWR REDHEAD",
    "SWR Redhead combo 2x10 (Eminence)",
  ],
  [
    "ACD_GKCX410",
    "GK-410",
    "cab4",
    "bass",
    "4X10 ROCK BOTTOM",
    "Gallien-Krueger 4x10 (GK)",
  ],
  [
    "ACD_FenBassman410Neo",
    "BM-410N",
    "cab4",
    "fenderbass",
    "4X10 BASSMAN PRO NEO",
    "Fender Bassman 410 Neo 4x10 (Eminence neo)",
  ],
  [
    "ACD_FenBassman610Neo",
    "BM-610N",
    "cab6",
    "fenderbass",
    "6X10 BASSMAN PRO NEO",
    "Fender Bassman 610 Neo 6x10 (Eminence neo)",
  ],
  [
    "ACD_FenBassman810Neo",
    "BM-810N",
    "cab8",
    "fenderbass",
    "8X10 BASSMAN PRO NEO",
    "Fender Bassman 810 Neo 8x10 (Eminence neo)",
  ],
  [
    "ACD_Ampeg810E",
    "SVT-810",
    "cab8",
    "ampeg",
    "8X10 RAMPAGE BASS",
    "Ampeg SVT-810 8x10",
  ],
  [
    "ACD_FenBassman115Neo",
    "BM-115N",
    "cab15",
    "fenderbass",
    "1X15 BASSMAN PRO NEO",
    "Fender Bassman 115 Neo 1x15 (Eminence neo)",
  ],
  [
    "ACD_BassmanTV115",
    "BTV-115",
    "cab15",
    "tweed",
    "1X15 BASSMAN TV",
    "Fender Bassman TV 1x15 (Celestion)",
  ],
  [
    "ACD_FlipTop",
    "B15-115",
    "cab15",
    "fliptop",
    "1X15 RAMPAGE BASS",
    "Ampeg B-15 'flip top' 1x15 (CTS)",
  ],
  // — firmware / Pro Control only (not in printed Model Guide 1.7) —
  [
    "ACD_CabSimTMS",
    "CAB-IR",
    "cab1",
    "ink",
    "CABINET (IR BLOCK)",
    "Fender — cabinet / IR block container",
    false,
  ],
  [
    "ACD_British212AlnicoBlue",
    "M2-BLU",
    "cab2",
    "marshall",
    "2X12 BRITISH ALNICO BLUE",
    "Marshall 'Bluesbreaker' 2x12 (Celestion Alnico Blue)",
    false,
  ],
  [
    "ACD_FenSuperSonic100_412SLST_v30",
    "SS-412",
    "cab4",
    "blackface",
    "4X12 SUPER-SONIC",
    "Fender Super-Sonic 100 4x12 (Celestion V30)",
    false,
  ],
  [
    "ACD_Evh5150iii_412st",
    "5150-STR",
    "cab4",
    "boutique",
    "4X12 EVH 5150III (STRAIGHT)",
    "EVH 5150III 4x12 straight cabinet",
    false,
  ],
  [
    "ACD_FenBluesJrLTD_JensenSpecial",
    "BJR-JS",
    "cab1",
    "tweed",
    "1X12 BLUES JR LTD (JENSEN)",
    "Fender Blues Jr LTD 1x12 (Jensen Special Design)",
    false,
  ],
  [
    "ACD_Kasino_CTS_137_7014",
    "KAS-412",
    "cab4",
    "black",
    "4X12 KASINO CTS",
    "Kustom/Kasino 4x12 (CTS 137-7014)",
    false,
  ],
  [
    "ACD_Peavey5150_4x12_Sheffield_1200",
    "PV-412",
    "cab4",
    "black",
    "4X12 PEAVEY 5150 SHEFFIELD",
    "Peavey 5150 4x12 (Sheffield 1200)",
    false,
  ],
];
