import type { CatalogCategory } from "./types";

export const COMBO_CATEGORY: CatalogCategory = {
  key: "combo",
  label: "Combo Amps",
  blurb: "Modeled combo amplifiers (no separate cab).",
  blocks: [
    [
      "ACD_TweedDeluxe",
      "57DLX",
      "combo",
      "tweed",
      "FENDER '57 DELUXE",
      "Fender '57 Deluxe (5E3 tweed)",
    ],
    [
      "ACD_TM59Bassman",
      "59BASS",
      "combo",
      "tweed",
      "FENDER '59 BASSMAN",
      "Fender '59 Bassman (tweed 4x10)",
    ],
    [
      "ACD_TMCust59Bassman",
      "59BASS-C",
      "combo",
      "tweed",
      "FENDER '59 BASSMAN CUSTOM",
      "Fender '59 Bassman (modified, Greenbacks)",
    ],
    [
      "ACD_Princeton6G2",
      "62PRN",
      "combo",
      "brownface",
      "FENDER '62 PRINCETON",
      "Fender '62 Princeton (brownface 6G2)",
    ],
    [
      "ACD_PrincetonReverb65NoFx",
      "65PRN",
      "combo",
      "blackface",
      "FENDER '65 PRINCETON REVERB",
      "Fender '65 Princeton Reverb (blackface)",
    ],
    [
      "ACD_DeluxeReverb65NoFx",
      "65DLX",
      "combo",
      "blackface",
      "FENDER '65 DELUXE REVERB",
      "Fender '65 Deluxe Reverb (blackface)",
    ],
    [
      "ACD_DeluxeReverb65BlondeVibratoNoFx",
      "65DLX-BL",
      "combo",
      "blonde",
      "FENDER '65 DELUXE REVERB BLONDE NBC",
      "Fender '65 Deluxe Reverb (blonde, no bright cap)",
    ],
    [
      "ACD_TMSuperReverbNoFx",
      "65SUP",
      "combo",
      "blackface",
      "FENDER '65 SUPER REVERB",
      "Fender '65 Super Reverb (blackface 4x10)",
    ],
    [
      "ACD_TwinReverb65NoFx",
      "65TWN",
      "combo",
      "blackface",
      "FENDER '65 TWIN REVERB",
      "Fender '65 Twin Reverb (blackface)",
    ],
    [
      "ACD_TwinReverb65BlondeNoFx",
      "65TWN-BL",
      "combo",
      "blonde",
      "FENDER '65 TWIN REVERB BLONDE",
      "Fender '65 Twin Reverb (blonde, G12-65 Creamback)",
    ],
    [
      "ACD_Bassbreaker15",
      "BBRK",
      "combo",
      "blackface",
      "FENDER BASSBREAKER",
      "Fender Bassbreaker 15",
    ],
    [
      "ACD_BluesJrIV",
      "BJR",
      "combo",
      "blackface",
      "FENDER BLUES JUNIOR",
      "Fender Blues Junior IV",
    ],
    [
      "ACD_BluesJrIVLTD",
      "BJR-LTD",
      "combo",
      "tweed",
      "FENDER BLUES JUNIOR LTD",
      "Fender Blues Junior IV LTD (Jensen C12N)",
    ],
    [
      "ACD_VibroKing",
      "VIBKNG",
      "combo",
      "blonde",
      "FENDER VIBRO-KING",
      "Fender Vibro-King",
    ],
    [
      "ACD_JTM45TremCombo",
      "JTM45-C",
      "combo",
      "bluesbreaker",
      "BRIT BREAKER",
      "Marshall JTM45 'Bluesbreaker' combo (1962)",
    ],
    [
      "ACD_AC30Brilliant",
      "AC30-TB",
      "combo",
      "vox",
      "UK 30 BRILLIANT",
      "Vox AC30 (Brilliant / Top Boost channel)",
    ],
    [
      "ACD_AC30Normal",
      "AC30-N",
      "combo",
      "vox",
      "UK 30 NORMAL",
      "Vox AC30 (Normal channel)",
    ],
    [
      "ACD_MarkIICClassA",
      "MK2C-CL",
      "combo",
      "mesa",
      "MARKSMAN CH1",
      "Mesa/Boogie Mark IIC+ (clean channel)",
    ],
    [
      "ACD_JC120",
      "JC120",
      "combo",
      "roland",
      "JC CLEAN",
      "Roland JC-120 Jazz Chorus (clean channel)",
    ],
  ],
};
