import type { CatalogCategory } from "./types";

export const DELAY_CATEGORY: CatalogCategory = {
  key: "delay",
  label: "Delay",
  blurb: "Tape, BBD, digital, and ambient delays.",
  blocks: [
    [
      "ACD_SpaceEcho",
      "RE-201",
      "delay",
      "green",
      "SPACE DELAY",
      "Roland RE-201 Space Echo",
    ],
    [
      "ACD_SpaceEchoStereo",
      "RE201 ST",
      "delay",
      "green",
      "STEREO SPACE DELAY",
      "Roland RE-201 Space Echo (stereo)",
    ],
    [
      "ACD_EchoplexEP3",
      "EP-3",
      "delay",
      "black",
      "TAPE ECHO",
      "Maestro Echoplex EP-3",
    ],
    [
      "ACD_EchoplexEP3Stereo",
      "EP-3 ST",
      "delay",
      "black",
      "STEREO TAPE ECHO",
      "Maestro Echoplex EP-3 (stereo)",
    ],
    [
      "ACD_DM2",
      "DM-2",
      "delay",
      "red",
      "ANALOG DELAY",
      "Boss DM-2 (bucket-brigade)",
    ],
    [
      "ACD_EchoMachine",
      "EM5",
      "delay",
      "teal",
      "ECHOTANK",
      "Ibanez Soundtank EM5 Echomachine",
    ],
    [
      "ACD_MemoryMan",
      "DMM",
      "delay",
      "chrome",
      "MEMORY DELAY",
      "Electro-Harmonix Deluxe Memory Man",
    ],
    [
      "ACD_MemoryManStereo",
      "DMM ST",
      "delay",
      "chrome",
      "STEREO MEMORY DELAY",
      "Electro-Harmonix Deluxe Memory Man (stereo)",
    ],
    [
      "ACD_BoilerPlateMono",
      "DIGITL",
      "delay",
      "pink",
      "DIGITAL DELAY",
      "Fender original (clean digital delay)",
    ],
    [
      "ACD_BoilerPlateStereo",
      "DIG ST",
      "delay",
      "mint",
      "STEREO DIGITAL DELAY",
      "Fender original (clean digital delay, stereo)",
    ],
    [
      "ACD_HoldDelay",
      "DD-3",
      "delay",
      "chrome",
      "DIGITAL HOLD DELAY",
      "Boss DD-3 (Hold mode)",
    ],
    [
      "ACD_HoldDelayStereo",
      "DD-3 ST",
      "delay",
      "chrome",
      "STEREO DIGITAL HOLD DELAY",
      "Boss DD-3 (Hold mode, stereo)",
    ],
    [
      "ACD_ModDelay",
      "2290",
      "delay",
      "graphite",
      "STUDIO DELAY",
      "TC Electronic 2290",
    ],
    [
      "ACD_DynamicDelay",
      "2290 DYN",
      "delay",
      "teal",
      "DYNAMIC DELAY",
      "TC Electronic 2290 (dynamic/stereo)",
    ],
    ["ACD_HaloDelay", "HALO", "delay", "black", "AURORA DELAY", "Keeley Halo"],
    [
      "ACD_HaloDelayStereo",
      "HALO ST",
      "delay",
      "black",
      "STEREO AURORA DELAY",
      "Keeley Halo (stereo)",
    ],
    [
      "ACD_RackDelay",
      "PCM42",
      "delay",
      "graphite",
      "ECHELON DELAY",
      "Lexicon PCM42",
    ],
    [
      "ACD_RackDelayStereo",
      "PCM42 ST",
      "delay",
      "graphite",
      "STEREO ECHELON DELAY",
      "Lexicon PCM42 (stereo)",
    ],
    [
      "ACD_MultiplyDelayMono",
      "PRIME",
      "delay",
      "graphite",
      "PRIME DELAY",
      "Lexicon Prime Time",
    ],
    [
      "ACD_MultiplyDelay",
      "PRIME ST",
      "delay",
      "graphite",
      "STEREO PRIME DELAY",
      "Lexicon Prime Time (stereo)",
    ],
    [
      "ACD_AutoSwellDelay",
      "SWELL",
      "delay",
      "teal",
      "AUTO-SWELL DELAY",
      "Fender original (swell delay)",
    ],
    [
      "ACD_TMDelayFilter",
      "ECHOFL",
      "delay",
      "cyan",
      "ECHO FILTER",
      "Fender original (resonant filter delay)",
    ],
    [
      "ACD_TMDelayFilterStereo",
      "ECHF ST",
      "delay",
      "cyan",
      "ECHO FILTER STEREO",
      "Fender original (resonant filter delay, stereo)",
    ],
    [
      "ACD_TMPingPong",
      "PNGPNG",
      "delay",
      "amber",
      "PING PONG DELAY",
      "Fender original (ping-pong stereo delay)",
    ],
    [
      "ACD_TMReverse",
      "REVRSE",
      "delay",
      "green",
      "REVERSE DELAY",
      "Fender original (reverse delay)",
    ],
    [
      "ACD_Polyhedron",
      "POLYHD",
      "delay",
      "pink",
      "POLYHEDRON PITCH DELAY",
      "Fender original (dual pitch-shift delay)",
    ],
    [
      "ACD_Glooper",
      "GLOOP",
      "delay",
      "graphite",
      "GLOOPER",
      "Fender original (glitch looper/delay)",
    ],
    [
      "ACD_Freeze",
      "FREEZE",
      "delay",
      "ice",
      "ARCTIC SUSTAINER",
      "Electro-Harmonix Freeze",
    ],
    [
      "ACD_DeepFreeze",
      "DEEPFRZ",
      "delay",
      "slate",
      "ANTARCTIC SUSTAINER",
      "Electro-Harmonix Deep Freeze",
    ],
    [
      "ACD_Doubler",
      "DOUBLR",
      "delay",
      "graphite",
      "STEREO DOUBLER",
      "Fender original (multi-track doubler)",
    ],
  ],
};
