import type { CatalogCategory } from "./types";

export const DRIVE_CATEGORY: CatalogCategory = {
  key: "drive",
  label: "Stompbox / Drive",
  blurb: "Boost, overdrive, distortion, fuzz.",
  blocks: [
    [
      "ACD_Boost",
      "BOOST",
      "boost",
      "chrome",
      "BOOST",
      "Fender original (clean boost)",
    ],
    [
      "ACD_Rangemaster",
      "RANGE",
      "boost",
      "chrome",
      "RANGER BOOST",
      "Dallas Rangemaster Treble Booster",
    ],
    [
      "ACD_RackPreamp",
      "SDD3000",
      "knobs2",
      "navy",
      "SDD-BOOST",
      "Korg SDD-3000 (preamp section)",
    ],
    [
      "ACD_EPBooster",
      "EP-BST",
      "boost",
      "black",
      "XO BOOST",
      "Xotic EP Booster (Echoplex EP-3 preamp)",
    ],
    [
      "ACD_BluesBreaker",
      "BLUESBK",
      "od",
      "black",
      "BLUES MAKER",
      "Marshall Bluesbreaker",
    ],
    [
      "ACD_KingOfTone",
      "KOT",
      "od",
      "plum",
      "ROYAL TONE",
      "Analogman Prince of Tone",
    ],
    [
      "ACD_TimmyV3",
      "TIMMY",
      "od",
      "blue",
      "ENCHANTER",
      "Paul Cochrane Timmy 15th Anniversary V3",
    ],
    [
      "ACD_TubeScreamer",
      "TS808",
      "od",
      "green",
      "GREENBOX 8",
      "Ibanez TS808 Tube Screamer",
    ],
    [
      "ACD_Greenbox10",
      "TS-10",
      "od",
      "green",
      "GREENBOX 10",
      "Ibanez TS-10 Tube Screamer",
    ],
    [
      "ACD_BluesDriver",
      "BD-2",
      "od",
      "blue",
      "SAPPHIRE DRIVE",
      "Boss BD-2 Blues Driver",
    ],
    [
      "ACD_MythicDrive",
      "KLON",
      "knobs3",
      "gold",
      "MYTHIC DRIVE",
      "Klon Centaur",
    ],
    [
      "ACD_KlonCentaur",
      "KLON-S",
      "knobs3",
      "chrome",
      "MYTHIC DRIVE II",
      "Klon Centaur 'No Horse' (silver)",
    ],
    [
      "ACD_NobelsOdr1",
      "ODR-1",
      "od",
      "green",
      "NASHVILLE OVERDRIVE",
      "Nobels ODR-1BC",
    ],
    [
      "ACD_TubeDriver",
      "TUBEDR",
      "knobs4",
      "muff",
      "TUBE OD",
      "B.K. Butler Tube Driver",
    ],
    [
      "ACD_SD1",
      "SD-1",
      "od",
      "yellow",
      "SUPERDRIVE",
      "Boss SD-1 Super Overdrive",
    ],
    ["ACD_DS1", "DS-1", "od", "orange", "ORANGEBOX", "Boss DS-1 Distortion"],
    [
      "ACD_DistortionPlus",
      "DIST+",
      "knobs2",
      "yellow",
      "HARD-CLIP DISTORTION",
      "MXR Distortion+",
    ],
    [
      "ACD_Palladium",
      "PALLAD",
      "knobs6",
      "graphite",
      "MAXIMUS DRIVE",
      "Seymour Duncan Palladium Gain Stage",
    ],
    [
      "ACD_Pugilist",
      "PUGIL",
      "knobs6",
      "yellow",
      "PUGILIST DISTORTION",
      "Fender original (dual-engine distortion)",
    ],
    [
      "ACD_ObsessiveDrive",
      "OCD",
      "od",
      "muff",
      "CSD (COMIC SANS DRIVE)",
      "Fulltone OCD",
    ],
    [
      "ACD_ZenDrive",
      "ZENDRV",
      "knobs4",
      "cream",
      "NAMASTE DRIVE",
      "Hermida Audio Zendrive",
    ],
    [
      "ACD_JRockettDude",
      "DUDE",
      "knobs4",
      "black",
      "ROCKET MAN",
      "J. Rockett The Dude",
    ],
    ["ACD_Rat", "RAT", "od", "rat", "RODENT", "Pro Co RAT"],
    [
      "ACD_BigFuzz",
      "BMP-NYC",
      "bigmuff",
      "chrome",
      "BIG APPLE FUZZ",
      "Electro-Harmonix NYC Big Muff Pi",
    ],
    [
      "ACD_GreenRussianBmp",
      "BMP-RUSS",
      "bigmuff",
      "olive",
      "BIG GREEN FUZZ",
      "Electro-Harmonix Green Russian Big Muff Pi",
    ],
    [
      "ACD_RamsHeadBmp",
      "BMP-RH",
      "bigmuff",
      "ramshead",
      "BIG HORN FUZZ",
      "Electro-Harmonix Ram's Head Big Muff Pi",
    ],
    [
      "ACD_GeFuzzFace",
      "FF-GE",
      "roundfuzz",
      "fuzzface",
      "ROUND FUZZ (GERMANIUM)",
      "Dallas Arbiter Fuzz Face (germanium)",
    ],
    [
      "ACD_RoundFuzz",
      "FF-SI",
      "roundfuzz",
      "siliconfuzz",
      "ROUND FUZZ (SILICON)",
      "Dallas Arbiter Fuzz Face (silicon)",
    ],
    [
      "ACD_VariFuzz",
      "TWEAK",
      "fuzz",
      "yellow",
      "VARI FUZZ",
      "Seymour Duncan Tweak Fuzz",
    ],
    [
      "ACD_Octavia",
      "OCTAVIA",
      "fuzz",
      "blue",
      "OCTAVE FUZZ",
      "Tycobrahe Octavia",
    ],
    [
      "ACD_Octobot",
      "OCTBOT",
      "fuzz",
      "ice",
      "OCTOBOT",
      "Fender original (octave-up/down fuzz)",
    ],
    [
      "ACD_ModernBassOverdrive",
      "BDDI",
      "knobs6",
      "black",
      "BASS OVERDRIVE",
      "Tech 21 SansAmp (Bass Driver)",
    ],
  ],
};
