import type { CatalogCategory } from "./types";

export const DYN_CATEGORY: CatalogCategory = {
  key: "dyn",
  label: "Dynamics",
  blurb: "Compressors, sustain, gates, volume / swell.",
  blocks: [
    [
      "ACD_DynaComp",
      "DYNA",
      "comp",
      "red",
      "DYNAMIC COMPRESSOR",
      "MXR Dyna Comp",
    ],
    [
      "ACD_CS3",
      "CS-3",
      "comp",
      "blue",
      "PEDAL COMP",
      "Boss CS-3 Compression Sustainer",
    ],
    [
      "ACD_CompressorSimple",
      "DYNA-S",
      "comp",
      "ink",
      "SIMPLE COMPRESSOR",
      "MXR Dyna Comp (simplified)",
    ],
    [
      "ACD_CompressorSimpleSoftKnee",
      "STUCMP",
      "comp",
      "ink",
      "STUDIO COMPRESSOR",
      "Fender original (studio comp, soft-knee)",
    ],
    ["ACD_Sustain", "M163", "comp", "black", "SUSTAIN", "MXR M-163 Sustain"],
    [
      "ACD_ChromeGate",
      "DECIM",
      "gate",
      "chrome",
      "METAL GATE",
      "ISP Technologies Decimator II G String",
    ],
    [
      "ACD_NoiseGate",
      "GATE",
      "gate",
      "black",
      "NOISE GATE",
      "Fender original (noise gate)",
    ],
    [
      "ACD_NoiseGateMustang",
      "SMPGAT",
      "gate",
      "gold",
      "SIMPLE GATE",
      "Fender original (simplified noise gate)",
    ],
    [
      "ACD_VolumePedal",
      "VOL",
      "treadle",
      "ink",
      "VOLUME PEDAL",
      "Fender original (volume pedal)",
    ],
    [
      "ACD_VolumeSwell",
      "A-SWLL",
      "vol",
      "red",
      "AUTO-SWELL VOLUME",
      "Fender original (auto volume swell)",
    ],
    [
      "ACD_SlowAttack",
      "SLOWAT",
      "vol",
      "black",
      "SLOW ATTACK",
      "Electro-Harmonix POG ('Attack' parameter)",
    ],
  ],
};
