import type { CatalogCategory } from "./types";

export const EQ_CATEGORY: CatalogCategory = {
  key: "eq",
  label: "EQ",
  blurb: "Graphic & parametric EQ, pass / notch filters.",
  blocks: [
    [
      "ACD_MustangFiveBandEq1",
      "EQ5-GR",
      "eq5",
      "black",
      "EQ5 GRAPHIC",
      "Mesa/Boogie Mark IIC+ 5-band graphic EQ",
    ],
    [
      "ACD_MustangSevenBandEq",
      "GE-7",
      "eq7",
      "muff",
      "EQ7 GRAPHIC",
      "Boss GE-7",
    ],
    [
      "ACD_TMBassGraphicEQ7",
      "EQ7B",
      "eq7",
      "muff",
      "EQ-7B BASS GRAPHIC",
      "Fender original (7-band bass graphic)",
    ],
    [
      "ACD_TMGraphicEQ7Wide",
      "EQ7W",
      "eq7",
      "wood",
      "EQ-7W WIDE-RANGE BASS GRAPHIC",
      "Fender original (7-band wide bass graphic)",
    ],
    [
      "ACD_TenBandEQStereo",
      "EQ10 ST",
      "eq10",
      "chrome",
      "EQ-10 GRAPHIC",
      "Fender original (10-band graphic)",
    ],
    [
      "ACD_TenBandEQMono",
      "EQ10",
      "eq10",
      "chrome",
      "EQ10 MONO",
      "Fender original (10-band graphic EQ, mono)",
    ],
    [
      "ACD_MustangPEQ",
      "EQ3-P",
      "peq",
      "chrome",
      "EQ-3 PARAMETRIC",
      "Fender original (3-band parametric)",
    ],
    [
      "ACD_FiveBandParamEQ",
      "EQ5-P",
      "screen",
      "slate",
      "EQ-5 PARAMETRIC",
      "Fender original (5-band parametric)",
    ],
    [
      "ACD_HighLowPass",
      "LO/HI",
      "screen",
      "slate",
      "LOW/HIGH CUT FILTER",
      "Fender original (dual low+high cut)",
    ],
    [
      "ACD_LowPass",
      "HICUT",
      "screen",
      "slate",
      "HIGH CUT FILTER",
      "Fender original (low-pass / high-cut)",
    ],
    [
      "ACD_HighPass",
      "LOCUT",
      "screen",
      "slate",
      "LOW CUT FILTER",
      "Fender original (high-pass / low-cut)",
    ],
    [
      "ACD_NotchFilter",
      "NOTCH",
      "screen",
      "slate",
      "NOTCH FILTER",
      "Fender original (notch filter)",
    ],
  ],
};
