import type { CatalogCategory } from "./types";

// ── firmware 1.8 additions (41 menu-exposed new models) ──────────────────
// icon/tone per the 1.8 Models-tab illustration handoff; ids + names from the
// 1.8.45 model-leaks inventory. Each per-form variant id is keyed explicitly so
// it renders its own form (head=amp icon, combo=combo icon) instead of relying
// on resolveBlockArt's suffix-stripping. `short` carries the engine's label-keyed
// discriminator (EVH GREEN/BLUE/RED accent · Twin 15 · gear-pedal name · 76).
export const FW18_CATEGORY: CatalogCategory = {
  key: "fw18",
  label: "Firmware 1.8",
  blurb: "Models added in Tone Master Pro firmware 1.8.",
  blocks: [
    [
      "ACD_TMChamp57",
      "57CHMP",
      "amp",
      "tweed",
      "'57 CHAMP",
      "Fender '57 Champ (5F1 tweed 1x8)",
    ],
    [
      "ACD_TMChamp57CabIR",
      "57CHMP",
      "combo",
      "tweed",
      "'57 CHAMP",
      "Fender '57 Champ (5F1 tweed 1x8)",
    ],
    [
      "ACD_PrincetonReverb68NoFx",
      "68PRN-A",
      "amp",
      "silverface",
      "'68 CUSTOM PRINCETON REVERB (AMP ONLY)",
      "Fender '68 Custom Princeton Reverb (silverface)",
    ],
    [
      "ACD_PrincetonReverb68NoFxCabIR",
      "68PRN-A",
      "combo",
      "silverface",
      "'68 CUSTOM PRINCETON REVERB (AMP ONLY)",
      "Fender '68 Custom Princeton Reverb (silverface)",
    ],
    [
      "ACD_PrincetonReverb68CabIRConvRvb",
      "68PRN",
      "combo",
      "silverface",
      "'68 CUSTOM PRINCETON REVERB",
      "Fender '68 Custom Princeton Reverb (silverface)",
    ],
    [
      "ACD_DeluxeReverb68CustomNoFx",
      "68DLX-A",
      "amp",
      "silverface",
      "'68 CUSTOM DELUXE REVERB (AMP ONLY)",
      "Fender '68 Custom Deluxe Reverb (silverface)",
    ],
    [
      "ACD_DeluxeReverb68CustomNoFxCabIR",
      "68DLX-A",
      "combo",
      "silverface",
      "'68 CUSTOM DELUXE REVERB (AMP ONLY)",
      "Fender '68 Custom Deluxe Reverb (silverface)",
    ],
    [
      "ACD_DeluxeReverb68CustomCabIRConvRvb",
      "68DLX",
      "combo",
      "silverface",
      "'68 CUSTOM DELUXE REVERB",
      "Fender '68 Custom Deluxe Reverb (silverface)",
    ],
    [
      "ACD_HypersonicAmp6L6Green",
      "5150C-G",
      "amp",
      "evhmodern",
      "EVH 5150 III 6L6 GREEN COMBO",
      "EVH 5150 III 6L6 (green / clean channel)",
    ],
    [
      "ACD_HypersonicAmp6L6GreenCabIR",
      "5150C-G",
      "combo",
      "evhmodern",
      "EVH 5150 III 6L6 GREEN COMBO",
      "EVH 5150 III 6L6 (green / clean channel)",
    ],
    [
      "ACD_HypersonicAmp6L6Blue",
      "5150C-B",
      "amp",
      "evhmodern",
      "EVH 5150 III 6L6 BLUE COMBO",
      "EVH 5150 III 6L6 (blue / crunch channel)",
    ],
    [
      "ACD_HypersonicAmp6L6BlueCabIR",
      "5150C-B",
      "combo",
      "evhmodern",
      "EVH 5150 III 6L6 BLUE COMBO",
      "EVH 5150 III 6L6 (blue / crunch channel)",
    ],
    [
      "ACD_HypersonicAmp6L6Red",
      "5150C-R",
      "amp",
      "evhmodern",
      "EVH 5150 III 6L6 RED COMBO",
      "EVH 5150 III 6L6 (red / lead channel)",
    ],
    [
      "ACD_HypersonicAmp6L6RedCabIR",
      "5150C-R",
      "combo",
      "evhmodern",
      "EVH 5150 III 6L6 RED COMBO",
      "EVH 5150 III 6L6 (red / lead channel)",
    ],
    [
      "ACD_TMRumbleV3",
      "RMB800",
      "amp",
      "bass",
      "RUMBLE 800",
      "Fender Rumble 800 (class-D bass head)",
    ],
    [
      "ACD_TMRumbleV3CabIR",
      "RMB800",
      "combo",
      "bass",
      "RUMBLE 800",
      "Fender Rumble 800 (class-D bass head)",
    ],
    [
      "ACD_TwinReverbCustom15NoFxCabIR",
      "65TW15-A",
      "combo",
      "blackface",
      "'65 TWIN CUSTOM 15 (AMP ONLY)",
      "Fender '65 Twin Reverb Custom (1x15 Eminence)",
    ],
    [
      "ACD_TwinReverbCustom15VibratoCabIRConvRvb",
      "65TW15",
      "combo",
      "blackface",
      "'65 TWIN CUSTOM 15",
      "Fender '65 Twin Reverb Custom (1x15 Eminence)",
    ],
    [
      "ACD_Fen57Champ",
      "1X8-57",
      "cab1",
      "tweed",
      "1X8 '57 CHAMP",
      "Fender '57 Champ 1x8 (tweed)",
    ],
    [
      "ACD_FenPrincGB",
      "65PR-GB",
      "cab1",
      "blackface",
      "1X10 '65 PRINCETON GB",
      "Fender '65 Princeton Reverb 1x10 (Celestion G10 Greenback)",
    ],
    [
      "ACD_Fen68PrinceG10R30",
      "68PR-10",
      "cab1",
      "silverface",
      "1X10 '68 PRINCETON",
      "Fender '68 Custom Princeton 1x10 (silverface, G10R-30)",
    ],
    [
      "ACD_Fen65DlxGB",
      "65DL-GB",
      "cab1",
      "blackface",
      "1X12 '65 DELUXE GB",
      "Fender '65 Deluxe Reverb 1x12 (Celestion G12 Greenback)",
    ],
    [
      "ACD_Fen68DlxG12V70",
      "68DL-12",
      "cab1",
      "silverface",
      "1X12 '68 DELUXE",
      "Fender '68 Custom Deluxe 1x12 (silverface, Celestion V-70)",
    ],
    [
      "ACD_Hypersonic_112",
      "5150-112",
      "cab1",
      "evhblack",
      "1X12 EVH 5150 G12H",
      "EVH 5150 1x12 (Celestion G12H)",
    ],
    [
      "ACD_FenTwinEmi15",
      "65TW-15",
      "cab15",
      "blackface",
      "1X15 TWIN CUSTOM",
      "Fender '65 Twin Custom 1x15 (Eminence Special Design)",
    ],
    [
      "ACD_Evh412G12H30",
      "M4-H30",
      "cab4",
      "marshall",
      "4X12 BRITISH G12H",
      "Marshall 1960 4x12 (Celestion G12H-30)",
    ],
    [
      "ACD_StepTremolo",
      "STEPTR",
      "steptrem",
      "slate",
      "STEP TREMOLO",
      "Fender original (step / square-wave tremolo)",
    ],
    [
      "ACD_TCIntegratedPre",
      "TC-IP",
      "labboost",
      "graphite",
      "INTEGRATOR BOOST",
      "TC Electronic Integrated Preamp (boost)",
    ],
    [
      "ACD_TCIntegratedPreStatic",
      "FORT33",
      "gruntboost",
      "black",
      "GRUNT BOOST",
      "TC Electronic Integrated Preamp (fixed-gain boost)",
    ],
    [
      "ACD_Rockman",
      "ROCKMAN",
      "rockbox",
      "black",
      "ROCKBOX 100",
      "Rockman X100 (80s pocket headphone amp)",
    ],
    [
      "ACD_Lightspeed",
      "LSPEED",
      "od3",
      "blue",
      "LIGHTYEAR",
      "Greer Lightspeed Organic Overdrive",
    ],
    [
      "ACD_Plumes",
      "PLUMES",
      "od3",
      "green",
      "PINIONS",
      "EarthQuaker Devices Plumes (overdrive)",
    ],
    [
      "ACD_Blumes",
      "BLUMES",
      "od3",
      "yellow",
      "RUNES",
      "EarthQuaker Devices Plumes (bass overdrive voicing)",
    ],
    [
      "ACD_StepFilterDelay",
      "STPFDL",
      "stepfilterdelay",
      "slate",
      "STEP FILTER DELAY",
      "Fender original (step-filter delay)",
    ],
    [
      "ACD_SpectralDelay",
      "PRISM",
      "prismdelay",
      "graphite",
      "PRISMATIC DELAY",
      "Fender original (prismatic spectral delay)",
    ],
    [
      "ACD_CirrostratusLite",
      "CIRRO",
      "cirrusverb",
      "frost",
      "CIRROSTRATUS REVERB",
      "Fender original (Cirrostratus ambient reverb)",
    ],
    [
      "ACD_Cirrostratus",
      "CIRR-SV",
      "cirrussynthverb",
      "frost",
      "CIRROSTRATUS SYNTHVERB",
      "Fender original (Cirrostratus synth reverb)",
    ],
    [
      "ACD_SpectralReverb",
      "SPECRV",
      "spectralverb",
      "chrome",
      "SPECTRAL REVERB",
      "Fender original (spectral shimmer reverb)",
    ],
    [
      "ACD_UA1176",
      "1176",
      "rack",
      "slate",
      "SEVENTY SIXER COMPRESSOR",
      "Universal Audio 1176 (FET compressor)",
    ],
    [
      "ACD_StepFilter",
      "STPFLT",
      "stepfilter",
      "slate",
      "STEP FILTER",
      "Fender original (step / sequenced filter)",
    ],
    [
      "ACD_PitchSequencer",
      "PTCHSQ",
      "pitchseq",
      "slate",
      "PITCH SEQUENCER",
      "Fender original (pitch step-sequencer)",
    ],
  ],
};
