import type { CatalogCategory } from "./types";

export const HALFSTACK_CATEGORY: CatalogCategory = {
  key: "halfstack",
  label: "Half Stacks",
  blurb: "Each amp head shown on its default Tone Master Pro cabinet.",
  blocks: [
    [
      "ACD_Bassbreaker15High",
      "BBRK-H",
      "combo",
      "blackface",
      "FENDER BASSBREAKER HIGH",
      "Fender Bassbreaker 15 (high-gain voicing)",
    ],
    [
      "ACD_Bassbreaker15Med",
      "BBRK-M",
      "combo",
      "blackface",
      "FENDER BASSBREAKER MED",
      "Fender Bassbreaker 15 (medium-gain voicing)",
      false,
    ],
    [
      "ACD_JTM45Head",
      "JTM45",
      "amp",
      "marshall",
      "BRITISH 45",
      "Marshall JTM45 head",
    ],
    [
      "ACD_MarshallPlexi",
      "PLEXI",
      "amp",
      "marshall",
      "BRITISH PLEXI",
      "Marshall 1959 Super Lead 100 ('Plexi')",
    ],
    [
      "ACD_JCM800TMS",
      "JCM800",
      "amp",
      "marshall",
      "BRITISH 800",
      "Marshall JCM800 2204 (50W)",
    ],
    [
      "ACD_Jubilee",
      "JUB-CL",
      "amp",
      "jubilee",
      "BRITISH JUBILEE CLEAN",
      "Marshall Silver Jubilee 2553 (clean channel)",
    ],
    [
      "ACD_JubileeClip",
      "JUB-RH",
      "amp",
      "jubilee",
      "BRITISH JUBILEE RHYTHM",
      "Marshall Silver Jubilee 2553 (rhythm/clip channel)",
    ],
    [
      "ACD_JubileeLead",
      "JUB-LD",
      "amp",
      "jubilee",
      "BRITISH JUBILEE LEAD",
      "Marshall Silver Jubilee 2553 (lead channel)",
    ],
    [
      "ACD_HiwattDR103CanMod",
      "DR103",
      "amp",
      "hiwatt",
      "HIWAY 105",
      "Hiwatt DR105 (Canadian-import DR103)",
    ],
    [
      "ACD_BE100",
      "BE100",
      "amp",
      "friedman",
      "FBE-100",
      "Friedman BE-100 (lead channel)",
    ],
    [
      "ACD_Evh100SGreen",
      "5150H-G",
      "amp",
      "boutique",
      "EVH 5150IIIS 6L6 GREEN",
      "EVH 5150IIIS 6L6 (green / low-gain channel)",
    ],
    [
      "ACD_Evh100SBlue",
      "5150H-B",
      "amp",
      "boutique",
      "EVH 5150IIIS 6L6 BLUE",
      "EVH 5150IIIS 6L6 (blue / medium-gain channel)",
    ],
    [
      "ACD_Evh100SRed",
      "5150H-R",
      "amp",
      "boutique",
      "EVH 5150IIIS 6L6 RED",
      "EVH 5150IIIS 6L6 (red / high-gain channel)",
    ],
    [
      "ACD_SLO100",
      "SLO100",
      "amp",
      "boutique",
      "SOLO 100 OVERDRIVE",
      "Soldano SLO-100",
    ],
    [
      "ACD_OrangeRockerverb50MKIII",
      "RV50",
      "amp",
      "orange",
      "TANGERINE RV53",
      "Orange Rockerverb 50 MkIII",
    ],
    [
      "ACD_MarkIICClassAB",
      "MK2C-LD",
      "amp",
      "mesa",
      "MARKSMAN CH2",
      "Mesa/Boogie Mark IIC+ (lead channel)",
    ],
    [
      "ACD_DualRectifier",
      "RECTO",
      "amp",
      "recto",
      "DOUBLE WRECK",
      "Mesa/Boogie Dual Rectifier Solo head",
    ],
    [
      "ACD_DiezelVh4Ch3",
      "VH4",
      "amp",
      "boutique",
      "PETROL",
      "Diezel VH4 (channel 3)",
    ],
    [
      "ACD_Uberschall",
      "UBER",
      "amp",
      "boutique",
      "UBER",
      "Bogner Uberschall (lead channel)",
    ],
  ],
};
