import type { CatalogCategory } from "./types";

export const MOD_CATEGORY: CatalogCategory = {
  key: "mod",
  label: "Modulation",
  blurb: "Chorus, vibrato, flanger, phaser, tremolo, rotary, vibe.",
  blocks: [
    [
      "ACD_ChorusCE2",
      "CE-2",
      "chorus",
      "cyan",
      "ANALOG CHORUS",
      "Boss CE-2 Chorus",
    ],
    [
      "ACD_ChorusCE3",
      "CE-2 ST",
      "chorus",
      "cyan",
      "STEREO ANALOG CHORUS",
      "Boss CE-2 Chorus (stereo)",
    ],
    [
      "ACD_ChorusCE2B",
      "CE-2B",
      "chorus",
      "cyan",
      "ANALOG BASS CHORUS",
      "Boss CE-2B Bass Chorus",
    ],
    [
      "ACD_Chorus_CE5Mono",
      "CE-5",
      "chorus",
      "cyan",
      "CHORUS",
      "Boss CE-5 Chorus",
    ],
    [
      "ACD_Chorus_CE5Stereo",
      "CE-5 ST",
      "chorus",
      "cyan",
      "CHORUS STEREO",
      "Boss CE-5 Chorus (stereo)",
    ],
    [
      "ACD_DimensionChorus",
      "DC-2",
      "chorus",
      "purple",
      "3D CHORUS",
      "Boss DC-2 Dimension C",
    ],
    [
      "ACD_JC120ChorusEffect",
      "JC-CHO",
      "chorus",
      "roland",
      "JC CHORUS",
      "Roland JC-120 Jazz Chorus (chorus)",
    ],
    [
      "ACD_JC120VibratoEffect",
      "JC-VIB",
      "univibe",
      "roland",
      "JC VIBRATO",
      "Roland JC-120 Jazz Chorus (vibrato)",
    ],
    [
      "ACD_TriStereoChorus",
      "TRI-SC",
      "chorus",
      "black",
      "TRIPLE-DOUBLE CHORUS",
      "Dyno My Piano Tri-Stereo Chorus",
    ],
    [
      "ACD_VibratoVB2",
      "VB-2",
      "univibe",
      "blue",
      "ANALOG VIBRATO",
      "Boss VB-2 Vibrato",
    ],
    [
      "ACD_Flanger2p0Mono",
      "BF-3",
      "flanger",
      "purple",
      "FLANGER",
      "Boss BF-3 Flanger",
    ],
    [
      "ACD_Flanger2p0Stereo",
      "BF-3 ST",
      "flanger",
      "purple",
      "FLANGER STEREO",
      "Boss BF-3 Flanger (stereo)",
    ],
    [
      "ACD_ElectricMistress",
      "MISTRESS",
      "flanger",
      "chrome",
      "ELECTRIC FLANGER",
      "Electro-Harmonix Electric Mistress",
    ],
    [
      "ACD_EvhFlanger",
      "M117",
      "flanger",
      "black",
      "'70S FLANGER",
      "MXR Flanger (M117, 1970s)",
    ],
    [
      "ACD_StereoPanner",
      "ORBIT",
      "tremolo",
      "purple",
      "ORBIT STEREO PANNER",
      "Fender original (stereo auto-panner)",
    ],
    ["ACD_PhaserPH3", "PH-3", "phaser", "green", "PHASER", "Boss PH-3 Phaser"],
    [
      "ACD_PhaserP90",
      "PHASE90",
      "phaser",
      "orange",
      "PHASER 90",
      "MXR Phase 90",
    ],
    [
      "ACD_SmallStone",
      "SMSTONE",
      "phaser",
      "chrome",
      "LITTLE ROCK PHASER",
      "Electro-Harmonix Small Stone",
    ],
    [
      "ACD_TremoloSine",
      "TR-2",
      "tremolo",
      "teal",
      "TREMOLO",
      "Boss TR-2 Tremolo",
    ],
    [
      "ACD_TremoloHarmonic",
      "HARMTR",
      "tremolo",
      "vinyl",
      "HARMONIC TREMOLO",
      "Fender brownface harmonic vibrato (6G-era)",
    ],
    [
      "ACD_PanoVerbTremolo",
      "HARM ST",
      "tremolo",
      "vinyl",
      "STEREO HARMONIC TREMOLO",
      "Fender brownface harmonic vibrato (stereo)",
    ],
    [
      "ACD_TMDR65Tremolo",
      "OPT-TR",
      "tremolo",
      "blackface",
      "OPTICAL TREMOLO",
      "Fender blackface photoresistor tremolo (Twin)",
    ],
    [
      "ACD_TremoloBias",
      "BIASTR",
      "tremolo",
      "blackface",
      "TUBE BIAS TREMOLO",
      "Fender tube-bias tremolo (Princeton Reverb)",
    ],
    [
      "ACD_UniVibe",
      "UNIVIBE",
      "univibe",
      "black",
      "UNI-VERSE VIBE",
      "Univox Uni-Vibe",
    ],
    [
      "ACD_PinwheelLeslie122",
      "LES122",
      "rotary",
      "wood",
      "ROTARY SPEAKER 122",
      "Leslie 122 rotary speaker",
    ],
    [
      "ACD_PinwheelLeslie147",
      "LES147",
      "rotary",
      "woodlt",
      "ROTARY SPEAKER 147",
      "Leslie 147 rotary speaker",
    ],
    [
      "ACD_TMPinwheelVibratone",
      "VIBTON",
      "rotary",
      "chrome",
      "VIBRATONE",
      "Fender Vibratone (rotating baffle)",
    ],
  ],
};
