import type { CatalogCategory } from "./types";

export const PITCH_CATEGORY: CatalogCategory = {
  key: "pitch",
  label: "Pitch",
  blurb: "Octave, detune, harmonizer, whammy, granular.",
  blocks: [
    [
      "ACD_MicroPitch",
      "MICRO",
      "octave",
      "red",
      "MICRO SHIFTER",
      "Eventide Micro Pitch",
    ],
    [
      "ACD_ChromaticPitchShifter",
      "CHROMA",
      "octave",
      "black",
      "CHROMATIC PITCH SHIFTER",
      "Fender original (chromatic pitch shift)",
    ],
    [
      "ACD_POG",
      "POG2",
      "octslider",
      "chrome",
      "POLYGON OCTAVE SHIFTER",
      "Electro-Harmonix POG2",
    ],
    [
      "ACD_PolyChord",
      "POLYVC",
      "octave",
      "chrome",
      "POLYVOICE PITCH SHIFTER",
      "Fender original (3-voice polyphonic shifter)",
    ],
    [
      "ACD_DiatonicPitchShifter",
      "DIATON",
      "octave",
      "plum",
      "DIATONIC PITCH SHIFTER",
      "Fender original (intelligent harmony)",
    ],
    [
      "ACD_Freqout",
      "FREQOUT",
      "octave",
      "black",
      "FEEDBACK GENERATOR",
      "Fender original (feedback simulator)",
    ],
    [
      "ACD_WhammyV5Detune",
      "WHAM-DT",
      "whammy",
      "red",
      "PEDAL DETUNE",
      "DigiTech Whammy (detune mode)",
    ],
    [
      "ACD_WhammyV5Classic",
      "WHAMMY",
      "whammy",
      "red",
      "PEDAL SHIFTER",
      "DigiTech Whammy (whammy mode)",
    ],
    [
      "ACD_PolyPitchShifter",
      "CAPO",
      "octave",
      "black",
      "VIRTUAL CAPO",
      "Fender original (polyphonic capo)",
    ],
    [
      "ACD_GranularArp",
      "GRANAR",
      "octave",
      "slate",
      "GRANULAR ARPEGGIATOR",
      "Fender original (granular delay/pitch)",
    ],
  ],
};
