import type { CatalogCategory } from "./types";

export const REVERB_CATEGORY: CatalogCategory = {
  key: "reverb",
  label: "Reverb",
  blurb: "Spring, room, hall, plate, shimmer, convolution.",
  blocks: [
    [
      "ACD_TMSpring63",
      "SPR63",
      "spring",
      "brownface",
      "'63 SPRING REVERB",
      "Fender '63 outboard spring reverb",
    ],
    [
      "ACD_TMSpring63Conv",
      "SPR63C",
      "spring",
      "brownface",
      "'63 SPRING REVERB CONVOLUTION",
      "Fender '63 spring reverb (convolution)",
    ],
    [
      "ACD_TMSpring65",
      "SPR65",
      "spring",
      "blackface",
      "'65 SPRING REVERB",
      "Fender blackface spring reverb",
    ],
    [
      "ACD_TMSpring65Conv",
      "SPR65C",
      "spring",
      "blackface",
      "'65 SPRING REVERB CONVOLUTION",
      "Fender blackface spring reverb (convolution)",
    ],
    [
      "ACD_TMSmallRoom",
      "SM-ROOM",
      "hall",
      "lake",
      "SMALL ROOM REVERB",
      "Fender original (digital room)",
    ],
    [
      "ACD_TMLargeRoom",
      "LG-ROOM",
      "hall",
      "teal",
      "LARGE ROOM REVERB",
      "Fender original (digital room)",
    ],
    [
      "ACD_TMSmallHall",
      "SM-HALL",
      "hall",
      "gold",
      "SMALL HALL REVERB",
      "Fender original (digital hall)",
    ],
    [
      "ACD_TMLargeHall",
      "LG-HALL",
      "hall",
      "green",
      "LARGE HALL REVERB",
      "Fender original (digital hall)",
    ],
    [
      "ACD_FenderSmallModulatedHall",
      "MOD-SH",
      "hall",
      "gold",
      "MODULATED SMALL HALL REVERB",
      "Fender original (modulated hall)",
    ],
    [
      "ACD_FenderLargeModulatedHall",
      "MOD-LH",
      "hall",
      "green",
      "MODULATED LARGE HALL REVERB",
      "Fender original (modulated hall)",
    ],
    [
      "ACD_TMSmallPlate",
      "EMT-SM",
      "plate",
      "red",
      "SMALL PLATE REVERB",
      "EMT 140 plate (smaller)",
    ],
    [
      "ACD_TMLargePlate",
      "EMT-LG",
      "plate",
      "muff",
      "LARGE PLATE REVERB",
      "EMT 140 plate",
    ],
    [
      "ACD_CloudReverb",
      "CLOUD",
      "shimmer",
      "chrome",
      "CLOUD REVERB",
      "Fender original (ambient pitch-modulated)",
    ],
    [
      "ACD_TMShimmer",
      "CELEST",
      "shimmer",
      "ice",
      "CELESTIAL REVERB",
      "Fender original (dual-pitch atmospheric)",
    ],
    [
      "ACD_NebulaTamed",
      "NEBULA",
      "shimmer",
      "ink",
      "NEBULA REVERB",
      "Fender original (huge ambient)",
    ],
    [
      "ACD_NebulaReverse",
      "NEB-R",
      "shimmer",
      "ink",
      "REVERSE NEBULA REVERB",
      "Fender original (reverse ambient)",
    ],
    [
      "ACD_SlimmerShimmer",
      "SHIMER",
      "shimmer",
      "teal",
      "SHIMMER REVERB",
      "Fender original (reverb + 2-octave shift)",
    ],
    [
      "ACD_TMAmbienceConv",
      "ATMOS",
      "hall",
      "graphite",
      "ATMOSPHERE CONVOLUTION ROOM REVERB",
      "Fender original (convolution room)",
    ],
    [
      "ACD_TMChamberConv",
      "VAST",
      "hall",
      "ink",
      "VAST CONVOLUTION CHAMBER REVERB",
      "Fender original (convolution chamber)",
    ],
    [
      "ACD_TMCathedralConv",
      "ASCEN",
      "hall",
      "chrome",
      "ASCENSION CONVOLUTION HALL REVERB",
      "Fender original (convolution hall)",
    ],
    [
      "ACD_TMEtherealHallConv",
      "ETHERL",
      "hall",
      "lavender",
      "ETHEREAL CONVOLUTION HALL REVERB",
      "Fender original (convolution hall)",
    ],
    [
      "ACD_TMHallOfDoomConv",
      "IMPERM",
      "hall",
      "black",
      "IMPERIUM CONVOLUTION HALL REVERB",
      "Fender original (convolution hall)",
    ],
    [
      "ACD_TMNewAgeHallConv",
      "RETROG",
      "hall",
      "ink",
      "RETROGRADE CONVOLUTION HALL REVERB",
      "Fender original (convolution hall)",
    ],
    [
      "ACD_TMWarmPlateConv",
      "ALKALN",
      "plate",
      "muff",
      "ALKALINE CONVOLUTION PLATE REVERB",
      "Fender original (convolution plate)",
    ],
    [
      "ACD_TMRichPlateConv",
      "KINETC",
      "plate",
      "chrome",
      "KINETIC CONVOLUTION PLATE REVERB",
      "Fender original (convolution plate)",
    ],
  ],
};
