#!/usr/bin/env python3
"""Generate src/models/cabCovering.generated.ts from the TMP firmware.

The Tone Master Pro firmware's Qt client (`tone-master-stomp-client`) embeds
`:/stompapp-assets/metadata/DUBS_extender.json`, whose `modules[ampId]` records
carry `{ defaultCab, altCab, static, altStatic }`. Pro Control resolves an amp
tile's COVERING (tolex) from the amp id + the attached cab sim:

    covering = static            if cabsimid == defaultCab
             = altStatic[ i ]    where i = altCab.split(',').index(cabsimid)

The covering is the slug suffix (`_blonde`, `_tweed`, base = blackface/…). So a
blackface '65 Twin head + the cream Creamback cab renders BLONDE on the unit; the
companion (which keyed amp art on the amp id alone) showed blackface. This script
mirrors that table so the companion's strip matches the device.

We emit ONLY records whose covering actually changes with the cab (≥2 distinct
covering tones) — the Twin/Deluxe Reverb blackface↔blonde swaps and Blues Jr
blackface↔tweed. Pure head/combo FORM or speaker swaps (Bassbreaker, Princeton,
Vibro King, AC30, Bassman, Tweed Deluxe, JTM45) carry no covering change and are
skipped.

The firmware binary's zlib stream is located by SCANNING (zlib header + a probe
for `modules`/`defaultCab`), never a hardcoded virtual address — the offset is
firmware-version-specific. Re-run on a firmware rev:

    python3 scripts/extract_cab_covering.py [path-to-tone-master-stomp-client]
"""
import json
import sys
import zlib
from pathlib import Path

# Placeholder — pass the extracted client binary path as argv[1] (see usage above).
DEFAULT_BIN = Path("tone-master-stomp-client")
OUT = Path(__file__).resolve().parent.parent / "src/models/cabCovering.generated.ts"

# Slug covering token / family base → a companion ToneId (src/ui/blockart/shared.tsx).
# Only the families that appear in a covering-changing record are needed.
FAMILY_BASE_TONE = {
    "65_twin_reverb": "blackface",
    "65_deluxe_reverb": "blackface",
    "blues_jr": "blackface",
}
VALID_TONES = {"blackface", "blonde", "tweed"}


def slug_tone(slug: str) -> str | None:
    s = slug.lower()
    if "blonde" in s:
        return "blonde"
    if "tweed" in s:
        return "tweed"
    for fam, tone in FAMILY_BASE_TONE.items():
        if s.startswith(fam):
            return tone
    return None  # a family with no covering opinion → skip


def find_dubs(data: bytes) -> dict:
    for hdr in (b"\x78\x9c", b"\x78\xda", b"\x78\x01"):
        i = 0
        while True:
            i = data.find(hdr, i)
            if i < 0:
                break
            try:
                out = zlib.decompressobj().decompress(data[i : i + 4_000_000])
            except Exception:
                out = b""
            if len(out) > 50_000 and b"defaultCab" in out and b"modules" in out:
                return json.loads(out)
            i += 1
    raise SystemExit("DUBS_extender.json zlib stream not found in binary")


def strip_acd(cab: str) -> str:
    return cab[4:] if cab.startswith("ACD_") else cab


def main() -> None:
    bin_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_BIN
    data = bin_path.read_bytes()
    modules = find_dubs(data)["modules"]

    table: dict[str, dict[str, str]] = {}
    for amp_id, rec in modules.items():
        alt_cab = rec.get("altCab")
        if not alt_cab:
            continue
        static = rec.get("static", "")
        alt_static = [s.strip() for s in (rec.get("altStatic") or "").split(",")]
        # cab → its art slug (alt cab keeps `static` when its altStatic is empty/"None")
        pairs = [(rec.get("defaultCab", ""), static)]
        for idx, cab in enumerate(alt_cab.split(",")):
            slug = alt_static[idx] if idx < len(alt_static) else ""
            if not slug or slug == "None":
                slug = static
            pairs.append((cab.strip(), slug))

        tones = {cab: slug_tone(slug) for cab, slug in pairs if cab}
        distinct = {t for t in tones.values() if t}
        if len(distinct) < 2:
            continue  # form/speaker-only swap, no covering change → skip
        by_cab = {strip_acd(cab): t for cab, t in tones.items() if t}
        bad = set(by_cab.values()) - VALID_TONES
        if bad:
            raise SystemExit(f"{amp_id}: unmapped covering tone(s) {bad}")
        table[amp_id] = dict(sorted(by_cab.items()))

    table = dict(sorted(table.items()))
    body = ",\n".join(
        "  "
        + json.dumps(amp)
        + ": { "
        + ", ".join(f"{json.dumps(c)}: {json.dumps(t)}" for c, t in cabs.items())
        + " }"
        for amp, cabs in table.items()
    )
    ts = (
        "// GENERATED by scripts/extract_cab_covering.py — DO NOT EDIT.\n"
        "// Cab-driven amp covering (tolex), mirrored from the firmware Qt client's\n"
        "// DUBS_extender.json modules[ampId].{defaultCab,altCab,static,altStatic}.\n"
        "// Keyed by the device amp FenderId; inner key is the node's cabsimid (no\n"
        "// ACD_ prefix, as the device sends it) → the displayed covering ToneId.\n"
        "// Only covering-CHANGING amps are listed (Twin/Deluxe blackface↔blonde,\n"
        "// Blues Jr blackface↔tweed); form/speaker-only swaps are omitted.\n"
        'import type { ToneId } from "../ui/BlockArt";\n\n'
        "// Partial<Record<…>> so an indexed lookup is honestly `ToneId | undefined`\n"
        "// (the repo has no noUncheckedIndexedAccess; a plain Record would make the\n"
        "// resolver's `?.` lint as no-unnecessary-condition — see CLAUDE.md).\n"
        "export const CAB_COVERING: Partial<\n"
        "  Record<string, Partial<Record<string, ToneId>>>\n"
        "> = {\n"
        f"{body},\n"
        "};\n"
    )
    OUT.write_text(ts)
    # Match the repo's prettier style so the gate stays green and a re-run is a
    # no-op diff (the emitted long object literals would otherwise reflow).
    try:
        import subprocess

        subprocess.run(["bunx", "prettier", "--write", str(OUT)], check=True)
    except Exception as e:  # bun not on PATH in this shell — format manually
        print(f"  (prettier skipped: {e}; run `bunx prettier --write {OUT}`)")
    print(f"wrote {OUT} — {len(table)} amp records")
    for amp, cabs in table.items():
        print(f"  {amp}: {cabs}")


if __name__ == "__main__":
    main()
