// GENERATED by scripts/extract_cab_covering.py — DO NOT EDIT.
// Cab-driven amp covering (tolex), mirrored from the firmware Qt client's
// DUBS_extender.json modules[ampId].{defaultCab,altCab,static,altStatic}.
// Keyed by the device amp FenderId; inner key is the node's cabsimid (no
// ACD_ prefix, as the device sends it) → the displayed covering ToneId.
// Only covering-CHANGING amps are listed (Twin/Deluxe blackface↔blonde,
// Blues Jr blackface↔tweed); form/speaker-only swaps are omitted.
import type { ToneId } from "../ui/BlockArt";

// Partial<Record<…>> so an indexed lookup is honestly `ToneId | undefined`
// (the repo has no noUncheckedIndexedAccess; a plain Record would make the
// resolver's `?.` lint as no-unnecessary-condition — see CLAUDE.md).
export const CAB_COVERING: Partial<
  Record<string, Partial<Record<string, ToneId>>>
> = {
  ACD_BluesJrIV: {
    BlsJrIV_CelestionTypeA: "blackface",
    BlsJrIV_Jensen_C12N: "tweed",
  },
  ACD_BluesJrIVCabIR: {
    BlsJrIV_CelestionTypeA: "blackface",
    BlsJrIV_Jensen_C12N: "tweed",
  },
  ACD_BluesJrIVLTD: {
    BlsJrIV_CelestionTypeA: "blackface",
    BlsJrIV_Jensen_C12N: "tweed",
  },
  ACD_BluesJrIVLTDCabIR: {
    BlsJrIV_CelestionTypeA: "blackface",
    BlsJrIV_Jensen_C12N: "tweed",
  },
  ACD_DeluxeReverb65BlondeVibratoCabIRConvRvb: {
    Fen65DlxJBLD120f: "blackface",
    FenDlxRvbTMCream_g12neo: "blonde",
    FenDlxRvb_c12k: "blackface",
  },
  ACD_DeluxeReverb65BlondeVibratoNoFx: {
    Fen65DlxJBLD120f: "blackface",
    FenDlxRvbTMCream_g12neo: "blonde",
    FenDlxRvb_c12k: "blackface",
  },
  ACD_DeluxeReverb65BlondeVibratoNoFxCabIR: {
    Fen65DlxJBLD120f: "blackface",
    FenDlxRvbTMCream_g12neo: "blonde",
    FenDlxRvb_c12k: "blackface",
  },
  ACD_DeluxeReverb65NoFx: {
    Fen65DlxJBLD120f: "blackface",
    FenDlxRvbTMCream_g12neo: "blonde",
    FenDlxRvb_c12k: "blackface",
  },
  ACD_DeluxeReverb65NoFxCabIR: {
    Fen65DlxJBLD120f: "blackface",
    FenDlxRvbTMCream_g12neo: "blonde",
    FenDlxRvb_c12k: "blackface",
  },
  ACD_DeluxeReverb65VibratoCabIRConvRvb: {
    Fen65DlxJBLD120f: "blackface",
    FenDlxRvbTMCream_g12neo: "blonde",
    FenDlxRvb_c12k: "blackface",
  },
  ACD_TwinReverb65BlondeNoFx: {
    Fen65TwinJBLD120f: "blackface",
    FenTwnRvbTMCream_g12neo: "blonde",
    FenTwnRvb_Jensen_C12K: "blackface",
  },
  ACD_TwinReverb65BlondeNoFxCabIR: {
    Fen65TwinJBLD120f: "blackface",
    FenTwnRvbTMCream_g12neo: "blonde",
    FenTwnRvb_Jensen_C12K: "blackface",
  },
  ACD_TwinReverb65BlondeVibratoCabIRConvRvb: {
    Fen65TwinJBLD120f: "blackface",
    FenTwnRvbTMCream_g12neo: "blonde",
    FenTwnRvb_Jensen_C12K: "blackface",
  },
  ACD_TwinReverb65NoFx: {
    Fen65TwinJBLD120f: "blackface",
    FenTwnRvbTMCream_g12neo: "blonde",
    FenTwnRvb_Jensen_C12K: "blackface",
  },
  ACD_TwinReverb65NoFxCabIR: {
    Fen65TwinJBLD120f: "blackface",
    FenTwnRvbTMCream_g12neo: "blonde",
    FenTwnRvb_Jensen_C12K: "blackface",
  },
  ACD_TwinReverb65VibratoCabIRConvRvb: {
    Fen65TwinJBLD120f: "blackface",
    FenTwnRvbTMCream_g12neo: "blonde",
    FenTwnRvb_Jensen_C12K: "blackface",
  },
};
