// Maps a block FenderId (ACD_*) to its brand-lineage label for the Models
// detail-bar `lineage` meta cell. The 1.7 block is AUTO-GENERATED — do not
// hand-edit it: the design prototype's per-block tone map (catalog-data2.jsx)
// joined to TONE_LINEAGE (pedals.jsx), with 9 tones the prototype left unlabeled
// resolved to their intended brand (from PEDAL_TONES comments + each block's real
// unit). The source Model Guide JSON carries no lineage; this is the curated label
// set. The firmware-1.8 block at the END is hand-added (one entry per 1.8 addition
// id, derived from each model's real unit). Mics (bid===null) have no entry and
// fall back to "—" at the call site (see catalog.ts).
export const LINEAGE_BY_BID: Record<string, string> = {
  ACD_AC30Brilliant: "Vox",
  ACD_AC30Normal: "Vox",
  ACD_Acoustasonic: "Fender Acoustasonic",
  ACD_Ampeg66B15: "Ampeg",
  ACD_Ampeg810E: "Ampeg",
  ACD_AutoSwellDelay: "pitch · shimmer · freeze",
  ACD_BE100: "Friedman · SLO · EVH · Diezel",
  ACD_Bassbreaker15: "Fender blackface",
  ACD_Bassbreaker15High: "Fender blackface",
  ACD_Bassbreaker15Med: "Fender blackface",
  ACD_BassmanTV115: "Fender tweed",
  ACD_BigFuzz: "boost · silver · Memory Man",
  ACD_BlsJrIV_CelestionTypeA: "Fender blackface",
  ACD_BlsJrIV_Jensen_C12N: "Fender tweed",
  ACD_BluesBreaker: "Bluesbreaker · Boss · gate",
  ACD_BluesDriver: "Boss BD/CE · Timmy · Octavia",
  ACD_BluesJrIV: "Fender blackface",
  ACD_BluesJrIVLTD: "Fender tweed",
  ACD_Bogner_412STU_Celestion_G12H: "Friedman · SLO · EVH · Diezel",
  ACD_Bogner_412STU_Celestion_G12_V30: "Friedman · SLO · EVH · Diezel",
  ACD_BoilerPlateMono: "Fender DSP delays",
  ACD_BoilerPlateStereo: "Fender DSP delays",
  ACD_Boost: "boost · silver · Memory Man",
  ACD_British212Greenback: "Marshall",
  ACD_CS3: "Boss BD/CE · Timmy · Octavia",
  ACD_ChorusCE2: "Boss CE-2 · filter delay",
  ACD_ChorusCE2B: "Boss BD/CE · Timmy · Octavia",
  ACD_ChorusCE3: "Boss CE-2 · filter delay",
  ACD_Chorus_CE5Mono: "Boss BD/CE · Timmy · Octavia",
  ACD_Chorus_CE5Stereo: "Boss BD/CE · Timmy · Octavia",
  ACD_ChromaticPitchShifter: "Bluesbreaker · Boss · gate",
  ACD_ChromeGate: "boost · silver · Memory Man",
  ACD_CloudReverb: "boost · silver · Memory Man",
  ACD_CompressorSimple: "compressors · EQ panels",
  ACD_CompressorSimpleSoftKnee: "compressors · EQ panels",
  ACD_CryBabyGCB95: "Bluesbreaker · Boss · gate",
  ACD_CryBabyQ535: "Bluesbreaker · Boss · gate",
  ACD_CryBabyV847: "Bluesbreaker · Boss · gate",
  ACD_DM2: "Dyna Comp · DigiTech · plate",
  ACD_DS1: "Boss DS-1 · ping-pong",
  ACD_DeepFreeze: "EHX Deep Freeze",
  ACD_DeluxeReverb65BlondeVibratoNoFx: "Fender blonde",
  ACD_DeluxeReverb65NoFx: "Fender blackface",
  ACD_DiatonicPitchShifter: "panner · nebula · diatonic",
  ACD_Diezel412FV: "Friedman · SLO · EVH · Diezel",
  ACD_DiezelVh4Ch3: "Friedman · SLO · EVH · Diezel",
  ACD_DimensionChorus: "King of Tone · Flanger · Dimension",
  ACD_DistortionPlus: "Boss SD · MXR · VariFuzz",
  ACD_Doubler: "digital delay · poly",
  ACD_DualRectifier: "Mesa/Boogie",
  ACD_DynaComp: "Dyna Comp · DigiTech · plate",
  ACD_DynamicDelay: "Seymour Duncan · rack delay",
  ACD_EPBooster: "Bluesbreaker · Boss · gate",
  ACD_EchoMachine: "pitch · shimmer · freeze",
  ACD_EchoplexEP3: "Bluesbreaker · Boss · gate",
  ACD_EchoplexEP3Stereo: "Bluesbreaker · Boss · gate",
  ACD_ElectricMistress: "boost · silver · Memory Man",
  ACD_Evh100SBlue: "Friedman · SLO · EVH · Diezel",
  ACD_Evh100SGreen: "Friedman · SLO · EVH · Diezel",
  ACD_Evh100SRed: "Friedman · SLO · EVH · Diezel",
  ACD_Evh5150iii_4x12_Celestion_G12_EVH: "Friedman · SLO · EVH · Diezel",
  ACD_EvhFlanger: "Bluesbreaker · Boss · gate",
  ACD_ExternalCab: "wah · volume · utility",
  ACD_Fen57CustomDeluxe_eminence: "Fender tweed",
  ACD_Fen57DlxBlue: "Fender tweed",
  ACD_Fen65DlxJBLD120f: "Fender blackface",
  ACD_Fen65TwinJBLD120f: "Fender blackface",
  ACD_FenBassBreaker412V30: "Fender blackface",
  ACD_FenBassman115Neo: "SWR · GK · bass",
  ACD_FenBassman410Neo: "SWR · GK · bass",
  ACD_FenBassman610Neo: "SWR · GK · bass",
  ACD_FenBassman810Neo: "SWR · GK · bass",
  ACD_FenBassmanGB: "Fender tweed",
  ACD_FenBassman_Jensen_Special: "Fender tweed",
  ACD_FenBrownPrincetonCS12: "Fender brownface",
  ACD_FenBrownPrincetonJenC10R: "Fender brownface",
  ACD_FenDlxRvbTMCream_g12neo: "Fender blackface",
  ACD_FenDlxRvb_c12k: "Fender blackface",
  ACD_FenPrincetonRvb_jensen: "Fender blackface",
  ACD_FenSuperRvb_p10r: "Fender blackface",
  ACD_FenTwnRvbTMCream_g12neo: "Fender blackface",
  ACD_FenTwnRvb_Jensen_C12K: "Fender blackface",
  ACD_FenVibKng_p10rf: "Fender blackface",
  ACD_FenVibroKing_2x12_v30: "Fender blackface",
  ACD_Fen_Bassbreaker_Celestion_G12V_70: "Fender blackface",
  ACD_FenderLargeModulatedHall: "Klon · Pugilist · hall",
  ACD_FenderSmallModulatedHall: "Klon · Pugilist · hall",
  ACD_FiveBandParamEQ: "compressors · EQ panels",
  ACD_Flanger2p0Mono: "King of Tone · Flanger · Dimension",
  ACD_Flanger2p0Stereo: "King of Tone · Flanger · Dimension",
  ACD_FlipTop: "Ampeg",
  ACD_Freeze: "EHX Freeze",
  ACD_Freqout: "Bluesbreaker · Boss · gate",
  ACD_Fried_BE4x12_Greenback_V30: "Friedman · SLO · EVH · Diezel",
  ACD_Fried_BE4x12_V30_Greenback: "Friedman · SLO · EVH · Diezel",
  ACD_FxLoop1: "Fender blackface",
  ACD_FxLoop2: "Fender blackface",
  ACD_FxLoop3: "boost · silver · Memory Man",
  ACD_FxLoop3_4: "Ibanez · Nobels · Boss PH-3",
  ACD_FxLoop4: "Boss BD/CE · Timmy · Octavia",
  ACD_GK800RB: "Gallien-Krueger",
  ACD_GKCX410: "SWR · GK · bass",
  ACD_GeFuzzFace: "Fuzz Face (Ge)",
  ACD_Glooper: "Seymour Duncan · rack delay",
  ACD_GranularArp: "compressors · EQ panels",
  ACD_GreenRussianBmp: "Green Russian Muff",
  ACD_Greenbox10: "Ibanez · Nobels · Boss PH-3",
  ACD_GuitarSynth: "Orange",
  ACD_GuitarSynthLite: "Bluesbreaker · Boss · gate",
  ACD_HaloDelay: "Bluesbreaker · Boss · gate",
  ACD_HaloDelayStereo: "Bluesbreaker · Boss · gate",
  ACD_HighLowPass: "compressors · EQ panels",
  ACD_HighPass: "compressors · EQ panels",
  ACD_Hiwatt412Fane: "Hiwatt",
  ACD_HiwattDR103CanMod: "Hiwatt",
  ACD_HoldDelay: "boost · silver · Memory Man",
  ACD_HoldDelayStereo: "boost · silver · Memory Man",
  ACD_JC120: "Roland",
  ACD_JC120ChorusEffect: "Roland",
  ACD_JC120VibratoEffect: "Roland",
  ACD_JCM800TMS: "Marshall",
  ACD_JRockettDude: "Bluesbreaker · Boss · gate",
  ACD_JTM45Head: "Marshall",
  ACD_JTM45TremCombo: "Marshall",
  ACD_Jubilee: "Marshall Silver Jubilee",
  ACD_JubileeClip: "Marshall Silver Jubilee",
  ACD_JubileeLead: "Marshall Silver Jubilee",
  ACD_KingOfTone: "King of Tone · Flanger · Dimension",
  ACD_KlonCentaur: "boost · silver · Memory Man",
  ACD_KorgA2AutoWah: "boost · silver · Memory Man",
  ACD_LowPass: "compressors · EQ panels",
  ACD_Mar1960aV30: "Marshall",
  ACD_Mar1960aV30Alt: "Marshall",
  ACD_Mar1960tvGB: "Marshall",
  ACD_Mar212Cent100: "Marshall",
  ACD_Mar412Cent100: "Marshall",
  ACD_Mar412G1265: "Marshall",
  ACD_MarG12H30BB: "Marshall",
  ACD_MarkIICClassA: "Mesa/Boogie",
  ACD_MarkIICClassAB: "Mesa/Boogie",
  ACD_MarshallPlexi: "Marshall",
  ACD_Marshall_JCM800_1960A: "Marshall",
  ACD_Mbg412HBBSClosed: "Mesa/Boogie",
  ACD_Mbg_MkIICPlus_EVM12L: "Mesa/Boogie",
  ACD_Mbg_RectifierTrad_CelestionV30: "Mesa/Boogie",
  ACD_MemoryMan: "boost · silver · Memory Man",
  ACD_MemoryManStereo: "boost · silver · Memory Man",
  ACD_MicroPitch: "Dyna Comp · DigiTech · plate",
  ACD_MicroTronIV: "boost · silver · Memory Man",
  ACD_ModDelay: "Seymour Duncan · rack delay",
  ACD_ModernBassOverdrive: "Bluesbreaker · Boss · gate",
  ACD_Msh_Jubilee_Slant_Celestion_G12Vintage: "Marshall",
  ACD_MultiplyDelay: "Fender DSP delays",
  ACD_MultiplyDelayMono: "Fender DSP delays",
  ACD_MustangFiveBandEq1: "Bluesbreaker · Boss · gate",
  ACD_MustangPEQ: "compressors · EQ panels",
  ACD_MustangSevenBandEq: "Big Muff · cream plate",
  ACD_MythicDrive: "Klon · Pugilist · hall",
  ACD_NebulaReverse: "panner · nebula · diatonic",
  ACD_NebulaTamed: "panner · nebula · diatonic",
  ACD_NobelsOdr1: "Ibanez · Nobels · Boss PH-3",
  ACD_NoiseGate: "Bluesbreaker · Boss · gate",
  ACD_NoiseGateMustang: "Klon · Pugilist · hall",
  ACD_NotchFilter: "compressors · EQ panels",
  ACD_ObsessiveDrive: "Big Muff · cream plate",
  ACD_Octavia: "Boss BD/CE · Timmy · Octavia",
  ACD_Octobot: "Boss BD/CE · Timmy · Octavia",
  ACD_OrangePPC412: "Orange",
  ACD_OrangeRockerverb50MKIII: "Orange",
  ACD_POG: "boost · silver · Memory Man",
  ACD_Palladium: "Seymour Duncan · rack delay",
  ACD_PanoVerbTremolo: "harmonic tremolo",
  ACD_PhaserP90: "Orange",
  ACD_PhaserPH3: "Ibanez · Nobels · Boss PH-3",
  ACD_PinwheelLeslie122: "Leslie rotary",
  ACD_PinwheelLeslie147: "Leslie rotary",
  ACD_PolyChord: "boost · silver · Memory Man",
  ACD_PolyPitchShifter: "Bluesbreaker · Boss · gate",
  ACD_Polyhedron: "digital delay · poly",
  ACD_Princeton6G2: "Fender brownface",
  ACD_PrincetonReverb65NoFx: "Fender blackface",
  ACD_Pugilist: "Fulltone OCD",
  ACD_RackDelay: "Seymour Duncan · rack delay",
  ACD_RackDelayStereo: "Seymour Duncan · rack delay",
  ACD_RackPreamp: "Korg SDD-3000",
  ACD_RamsHeadBmp: "Big Muff (Ram's Head)",
  ACD_Rangemaster: "boost · silver · Memory Man",
  ACD_Rat: "ProCo RAT",
  ACD_Redhead: "SWR · GK · bass",
  ACD_Redhead210: "SWR · GK · bass",
  ACD_RolJazzChorus_JC120: "Roland",
  ACD_RoundFuzz: "Fuzz Face (Si)",
  ACD_SD1: "Boss SD · MXR · VariFuzz",
  ACD_SLO100: "Friedman · SLO · EVH · Diezel",
  ACD_SVTBlueLine: "Ampeg",
  ACD_SlimmerShimmer: "pitch · shimmer · freeze",
  ACD_SlowAttack: "Bluesbreaker · Boss · gate",
  ACD_SmallStone: "boost · silver · Memory Man",
  ACD_Sol_4x12_Slant_G12H: "Friedman · SLO · EVH · Diezel",
  ACD_SpaceEcho: "Ibanez · Nobels · Boss PH-3",
  ACD_SpaceEchoStereo: "Ibanez · Nobels · Boss PH-3",
  ACD_StereoPanner: "King of Tone · Flanger · Dimension",
  ACD_StudioPreamp: "compressors · EQ panels",
  ACD_StudioTubePreamp: "compressors · EQ panels",
  ACD_SuperBassman: "SWR · GK · bass",
  ACD_SuperBassmanVintage: "SWR · GK · bass",
  ACD_Sustain: "Bluesbreaker · Boss · gate",
  ACD_TM59Bassman: "Fender tweed",
  ACD_TMAmbienceConv: "convolution room",
  ACD_TMBassGraphicEQ7: "Big Muff · cream plate",
  ACD_TMBassmanTV: "Fender tweed",
  ACD_TMCathedralConv: "convolution hall",
  ACD_TMChamberConv: "convolution room",
  ACD_TMCust59Bassman: "Fender tweed",
  ACD_TMDR65Tremolo: "Fender blackface",
  ACD_TMDelayFilter: "Boss CE-2 · filter delay",
  ACD_TMDelayFilterStereo: "Boss CE-2 · filter delay",
  ACD_TMEtherealHallConv: "convolution hall",
  ACD_TMGraphicEQ7Wide: "Big Muff · cream plate",
  ACD_TMHallOfDoomConv: "Bluesbreaker · Boss · gate",
  ACD_TMLargeHall: "Klon · Pugilist · hall",
  ACD_TMLargePlate: "Big Muff · cream plate",
  ACD_TMLargeRoom: "room reverb",
  ACD_TMNewAgeHallConv: "room reverb",
  ACD_TMPingPong: "Boss DS-1 · ping-pong",
  ACD_TMPinwheelVibratone: "boost · silver · Memory Man",
  ACD_TMReverse: "Ibanez · Nobels · Boss PH-3",
  ACD_TMRichPlateConv: "King of Tone · Flanger · Dimension",
  ACD_TMShimmer: "pitch · shimmer · freeze",
  ACD_TMSmallHall: "Klon · Pugilist · hall",
  ACD_TMSmallPlate: "Dyna Comp · DigiTech · plate",
  ACD_TMSmallRoom: "room reverb",
  ACD_TMSpring63: "Fender brownface",
  ACD_TMSpring63Conv: "Fender brownface",
  ACD_TMSpring65: "Fender blackface",
  ACD_TMSpring65Conv: "Fender blackface",
  ACD_TMSuperReverbNoFx: "Fender blackface",
  ACD_TMWarmPlateConv: "Big Muff · cream plate",
  ACD_TenBandEQStereo: "boost · silver · Memory Man",
  ACD_TimmyV3: "Boss BD/CE · Timmy · Octavia",
  ACD_TremoloBias: "Fender blackface",
  ACD_TremoloHarmonic: "harmonic tremolo",
  ACD_TremoloSine: "pitch · shimmer · freeze",
  ACD_TriStereoChorus: "Bluesbreaker · Boss · gate",
  ACD_TubeDriver: "Big Muff · cream plate",
  ACD_TubeScreamer: "Ibanez · Nobels · Boss PH-3",
  ACD_TweedDeluxe: "Fender tweed",
  ACD_TwinReverb65BlondeNoFx: "Fender blonde",
  ACD_TwinReverb65NoFx: "Fender blackface",
  ACD_Uberschall: "Friedman · SLO · EVH · Diezel",
  ACD_UniVibe: "Bluesbreaker · Boss · gate",
  ACD_UserIRTMS: "wah · volume · utility",
  ACD_VariFuzz: "Boss SD · MXR · VariFuzz",
  ACD_VibratoVB2: "Boss BD/CE · Timmy · Octavia",
  ACD_VibroKing: "Fender blonde",
  ACD_VolumePedal: "wah · volume · utility",
  ACD_VolumeSwell: "Dyna Comp · DigiTech · plate",
  ACD_VoxAC30_Celestion_G12_Alinco_Blue: "Vox",
  ACD_VoxAC30_Celestion_Greenback: "Vox",
  ACD_WaveMorphSynth: "boost · silver · Memory Man",
  ACD_WhammyV5Classic: "Dyna Comp · DigiTech · plate",
  ACD_WhammyV5Detune: "Dyna Comp · DigiTech · plate",
  ACD_ZenDrive: "Hermida Zendrive",
  // ── firmware 1.8 additions (brand lineage for the detail-bar label) ──────
  ACD_TMChamp57: "Fender tweed",
  ACD_TMChamp57CabIR: "Fender tweed",
  ACD_PrincetonReverb68NoFx: "Fender silverface",
  ACD_PrincetonReverb68NoFxCabIR: "Fender silverface",
  ACD_PrincetonReverb68CabIRConvRvb: "Fender silverface",
  ACD_DeluxeReverb68CustomNoFx: "Fender silverface",
  ACD_DeluxeReverb68CustomNoFxCabIR: "Fender silverface",
  ACD_DeluxeReverb68CustomCabIRConvRvb: "Fender silverface",
  ACD_HypersonicAmp6L6Green: "EVH",
  ACD_HypersonicAmp6L6GreenCabIR: "EVH",
  ACD_HypersonicAmp6L6Blue: "EVH",
  ACD_HypersonicAmp6L6BlueCabIR: "EVH",
  ACD_HypersonicAmp6L6Red: "EVH",
  ACD_HypersonicAmp6L6RedCabIR: "EVH",
  ACD_TMRumbleV3: "Fender Rumble",
  ACD_TMRumbleV3CabIR: "Fender Rumble",
  ACD_TwinReverbCustom15NoFxCabIR: "Fender blackface",
  ACD_TwinReverbCustom15VibratoCabIRConvRvb: "Fender blackface",
  ACD_Fen57Champ: "Fender tweed",
  ACD_FenPrincGB: "Fender blackface",
  ACD_Fen68PrinceG10R30: "Fender silverface",
  ACD_Fen65DlxGB: "Fender blackface",
  ACD_Fen68DlxG12V70: "Fender silverface",
  ACD_Hypersonic_112: "EVH",
  ACD_FenTwinEmi15: "Fender blackface",
  ACD_Evh412G12H30: "EVH",
  ACD_StepTremolo: "Fender original",
  ACD_TCIntegratedPre: "TC Electronic",
  ACD_TCIntegratedPreStatic: "TC Electronic",
  ACD_Rockman: "Rockman",
  ACD_Lightspeed: "Greer",
  ACD_Plumes: "EarthQuaker Devices",
  ACD_Blumes: "EarthQuaker Devices",
  ACD_StepFilterDelay: "Fender original",
  ACD_SpectralDelay: "Fender original",
  ACD_CirrostratusLite: "Fender original",
  ACD_Cirrostratus: "Fender original",
  ACD_SpectralReverb: "Fender original",
  ACD_UA1176: "Universal Audio",
  ACD_StepFilter: "Fender original",
  ACD_PitchSequencer: "Fender original",
};
